name: Build and Push Docker Image

on:
  push:
    branches: [ master ]  # or master if your branch is master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Spring Boot app
        run: ./mvnw clean package -DskipTests

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: smm2004
          password: dckr_pat_w7YKl4r6hNC-Ap2vGFrlzztFza8

      - name: Build Docker image
        run: docker build -t smm2004/springboot-app .

      - name: Push Docker image
        run: docker push smm2004/springboot-app
